"""EvaluationScore

Revision ID: 2c05b057f1a5
Revises: b0de57f30350
Create Date: 2024-11-02 17:30:11.862313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c05b057f1a5'
down_revision: Union[str, None] = 'b0de57f30350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eval_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('explanation_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['explanation_id'], ['eval_plan_explanations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eval_scores')
    # ### end Alembic commands ###
